spring:
  datasource:
    url: ${FORGE_FLOW_DATASOURCE_URL:}
    username: ${FORGE_FLOW_DATASOURCE_USERNAME:push}
    password: ${FORGE_FLOW_DATASOURCE_PASSWORD:}

logging:
  level:
    com.forgeflow: debug
