CREATE TABLE llm_call_log (
  id BIGINT PRIMARY KEY COMMENT '主键ID',
  scene VARCHAR(64) NOT NULL COMMENT '调用场景',
  provider VARCHAR(64) NOT NULL COMMENT '模型供应商',
  model_name VARCHAR(128) NULL COMMENT '模型名称',
  status VARCHAR(32) NOT NULL COMMENT '调用状态',
  project_id BIGINT NULL COMMENT '项目ID',
  biz_type VARCHAR(64) NULL COMMENT '业务对象类型',
  biz_id BIGINT NULL COMMENT '业务对象ID',
  prompt_char_count INT NOT NULL DEFAULT 0 COMMENT 'Prompt字符数',
  response_char_count INT NOT NULL DEFAULT 0 COMMENT '返回内容字符数',
  attempt_count INT NOT NULL DEFAULT 1 COMMENT '调用尝试次数',
  elapsed_millis BIGINT NOT NULL DEFAULT 0 COMMENT '耗时毫秒',
  error_message TEXT NULL COMMENT '错误信息',
  started_at DATETIME NOT NULL COMMENT '开始时间',
  finished_at DATETIME NOT NULL COMMENT '结束时间',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  created_by BIGINT NULL COMMENT '创建人ID',
  updated_by BIGINT NULL COMMENT '更新人ID',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
  version INT NOT NULL DEFAULT 1 COMMENT '数据版本号',
  KEY idx_llm_scene (scene),
  KEY idx_llm_provider_model (provider, model_name),
  KEY idx_llm_status (status),
  KEY idx_llm_project_id (project_id),
  KEY idx_llm_biz (biz_type, biz_id),
  KEY idx_llm_started_at (started_at)
) COMMENT='LLM调用日志表';
