CREATE TABLE project (
  id BIGINT PRIMARY KEY COMMENT '主键ID',
  project_name VARCHAR(128) NOT NULL COMMENT '项目名称',
  project_code VARCHAR(64) NOT NULL COMMENT '项目编码',
  description VARCHAR(512) NULL COMMENT '项目描述',
  current_stage VARCHAR(64) NOT NULL COMMENT '当前阶段',
  status VARCHAR(64) NOT NULL COMMENT '项目状态',
  manager_id BIGINT NOT NULL COMMENT '项目经理ID',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  created_by BIGINT NULL COMMENT '创建人ID',
  updated_by BIGINT NULL COMMENT '更新人ID',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
  version INT NOT NULL DEFAULT 1 COMMENT '数据版本号',
  UNIQUE KEY uk_project_code (project_code),
  KEY idx_project_manager_id (manager_id),
  KEY idx_project_status (status)
) COMMENT='项目表';

CREATE TABLE audit_log (
  id BIGINT PRIMARY KEY COMMENT '主键ID',
  user_id BIGINT NULL COMMENT '操作人ID',
  user_role VARCHAR(64) NULL COMMENT '操作人角色',
  operation_type VARCHAR(64) NOT NULL COMMENT '操作类型',
  target_type VARCHAR(64) NOT NULL COMMENT '操作对象类型',
  target_id BIGINT NULL COMMENT '操作对象ID',
  before_content TEXT NULL COMMENT '操作前内容摘要',
  after_content TEXT NULL COMMENT '操作后内容摘要',
  ip_address VARCHAR(64) NULL COMMENT 'IP地址',
  user_agent VARCHAR(512) NULL COMMENT 'User Agent',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  created_by BIGINT NULL COMMENT '创建人ID',
  updated_by BIGINT NULL COMMENT '更新人ID',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
  version INT NOT NULL DEFAULT 1 COMMENT '数据版本号',
  KEY idx_audit_user_id (user_id),
  KEY idx_audit_target (target_type, target_id),
  KEY idx_audit_operation_type (operation_type)
) COMMENT='审计日志表';

CREATE TABLE requirement (
  id BIGINT PRIMARY KEY COMMENT '主键ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  title VARCHAR(128) NOT NULL COMMENT '需求标题',
  source_type VARCHAR(64) NOT NULL COMMENT '来源类型',
  priority VARCHAR(32) NOT NULL COMMENT '优先级',
  requester VARCHAR(128) NOT NULL COMMENT '需求方',
  product_owner VARCHAR(128) NOT NULL COMMENT '产品负责人',
  expected_date DATE NULL COMMENT '期望完成日期',
  background TEXT NOT NULL COMMENT '业务背景',
  objective TEXT NOT NULL COMMENT '目标与成功标准',
  scope TEXT NOT NULL COMMENT '范围与边界',
  original_content TEXT NULL COMMENT '原始需求内容',
  structured_summary TEXT NULL COMMENT '结构化摘要',
  missing_info TEXT NULL COMMENT '缺失信息',
  clarification_questions TEXT NULL COMMENT '澄清问题',
  material_count INT NOT NULL DEFAULT 0 COMMENT '材料数量',
  status VARCHAR(64) NOT NULL COMMENT '需求状态',
  version_no VARCHAR(32) NOT NULL COMMENT '版本号',
  sensitive_masked TINYINT NOT NULL DEFAULT 0 COMMENT '是否已脱敏：0否，1是',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  created_by BIGINT NULL COMMENT '创建人ID',
  updated_by BIGINT NULL COMMENT '更新人ID',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
  version INT NOT NULL DEFAULT 1 COMMENT '数据版本号',
  KEY idx_requirement_project_id (project_id),
  KEY idx_requirement_status (status)
) COMMENT='需求表';

CREATE TABLE prd_document (
  id BIGINT PRIMARY KEY COMMENT '主键ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  requirement_id BIGINT NOT NULL COMMENT '需求ID',
  title VARCHAR(128) NOT NULL COMMENT 'PRD标题',
  content MEDIUMTEXT NOT NULL COMMENT 'PRD内容',
  status VARCHAR(64) NOT NULL COMMENT 'PRD状态',
  version_no VARCHAR(32) NOT NULL COMMENT '版本号',
  frozen_at DATETIME NULL COMMENT '冻结时间',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  created_by BIGINT NULL COMMENT '创建人ID',
  updated_by BIGINT NULL COMMENT '更新人ID',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
  version INT NOT NULL DEFAULT 1 COMMENT '数据版本号',
  KEY idx_prd_project_id (project_id),
  KEY idx_prd_requirement_id (requirement_id),
  KEY idx_prd_status (status)
) COMMENT='PRD文档表';

CREATE TABLE generation_task (
  id BIGINT PRIMARY KEY COMMENT '主键ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  task_type VARCHAR(64) NOT NULL COMMENT '任务类型',
  status VARCHAR(64) NOT NULL COMMENT '任务状态',
  input_artifact_id BIGINT NULL COMMENT '输入产物ID',
  output_artifact_id BIGINT NULL COMMENT '输出产物ID',
  model_name VARCHAR(128) NULL COMMENT '模型名称',
  error_message TEXT NULL COMMENT '错误信息',
  started_at DATETIME NULL COMMENT '开始时间',
  finished_at DATETIME NULL COMMENT '结束时间',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  created_by BIGINT NULL COMMENT '创建人ID',
  updated_by BIGINT NULL COMMENT '更新人ID',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
  version INT NOT NULL DEFAULT 1 COMMENT '数据版本号',
  KEY idx_generation_project_id (project_id),
  KEY idx_generation_task_type (task_type),
  KEY idx_generation_status (status)
) COMMENT='AI生成任务表';
